# Generated by Django 4.1.3 on 2022-11-05 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_ft', models.IntegerField()),
                ('height_in', models.IntegerField()),
                ('looking_for', models.IntegerField(default=0)),
                ('target_gender', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=40)),
                ('year_of_study', models.IntegerField()),
                ('most_hated_course', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=40)),
                ('hometown', models.TextField()),
                ('bio', models.TextField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
