# Generated by Django 4.1.3 on 2022-11-06 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_userinfo_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='liked_users',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='liked_users',
            field=models.ManyToManyField(default=[], null=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
