# Generated by Django 4.1.3 on 2022-11-06 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userinfo_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='liked_users',
        ),
    ]
