# Generated by Django 4.1.3 on 2022-11-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userinfo_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='looking_for',
            field=models.CharField(max_length=40),
        ),
    ]
