# Generated by Django 4.1.3 on 2022-11-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hometown',
            field=models.CharField(max_length=50),
        ),
    ]
