# Generated by Django 4.1.3 on 2022-11-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swipe', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikedProfiles',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
