# Generated by Django 4.1.3 on 2022-11-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='index',
            new_name='message_index',
        ),
    ]
